FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel as base

RUN apt-get update -y
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y install python3.10
RUN apt-get -y install pip git vim

#ADD smartnet_tools/requirements.txt /smartnet_tools/requirements.txt
#RUN pip install -r /smartnet_tools/requirements.txt
#ADD smartnet_tools/requirements.txt /smartnet_tools/requirements.txt
#RUN pip install -r /smartnet_tools/requirements.txt